import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, bigint, boolean, date } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Uploaded files table for storing learning materials.
 */
export const uploadedFiles = mysqlTable("uploaded_files", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  filename: varchar("filename", { length: 512 }).notNull(),
  fileKey: varchar("fileKey", { length: 1024 }).notNull(),
  fileUrl: varchar("fileUrl", { length: 2048 }).notNull(),
  fileSize: bigint("fileSize", { mode: "number" }).notNull().default(0),
  mimeType: varchar("mimeType", { length: 128 }).notNull().default("application/octet-stream"),
  category: mysqlEnum("category", ["vocabulary", "grammar", "listening", "reading", "other"]).default("other").notNull(),
  description: text("description"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type UploadedFile = typeof uploadedFiles.$inferSelect;
export type InsertUploadedFile = typeof uploadedFiles.$inferInsert;

/**
 * Daily Korean articles generated by AI.
 * Each day gets up to 5 articles of different types.
 */
export const dailyArticles = mysqlTable("daily_articles", {
  id: int("id").autoincrement().primaryKey(),
  /** Date string in YYYY-MM-DD format (UTC+8 Beijing time) */
  contentDate: varchar("contentDate", { length: 10 }).notNull(),
  /** Korean title */
  title: varchar("title", { length: 512 }).notNull(),
  /** Chinese translation of title */
  titleZh: varchar("titleZh", { length: 512 }).notNull(),
  /** Full Korean article body */
  content: text("content").notNull(),
  /** Chinese translation of the article */
  contentZh: text("contentZh").notNull(),
  /** Article type: news, novel, blog, professional, social */
  articleType: mysqlEnum("articleType", ["news", "novel", "blog", "professional", "social"]).notNull(),
  /** Difficulty level: beginner, intermediate, advanced */
  difficulty: mysqlEnum("difficulty", ["beginner", "intermediate", "advanced"]).notNull().default("intermediate"),
  /** Key vocabulary words extracted from the article (JSON array of strings) */
  keyWords: text("keyWords"),
  /** Learning tips or grammar notes in Chinese */
  learningTips: text("learningTips"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type DailyArticle = typeof dailyArticles.$inferSelect;
export type InsertDailyArticle = typeof dailyArticles.$inferInsert;

/**
 * Daily MZ-generation Korean vocabulary.
 * Each day gets up to 5 vocabulary items.
 */
export const dailyVocabulary = mysqlTable("daily_vocabulary", {
  id: int("id").autoincrement().primaryKey(),
  /** Date string in YYYY-MM-DD format (UTC+8 Beijing time) */
  contentDate: varchar("contentDate", { length: 10 }).notNull(),
  /** Korean word or phrase */
  word: varchar("word", { length: 128 }).notNull(),
  /** Romanization/pronunciation guide */
  pronunciation: varchar("pronunciation", { length: 256 }),
  /** Chinese meaning/definition */
  meaning: text("meaning").notNull(),
  /** Usage context: slang, internet, youth, formal */
  wordType: mysqlEnum("wordType", ["slang", "internet", "youth", "formal", "expression"]).notNull().default("youth"),
  /** Example sentence in Korean */
  exampleSentence: text("exampleSentence").notNull(),
  /** Chinese translation of the example sentence */
  exampleTranslation: text("exampleTranslation").notNull(),
  /** Cultural context or background note in Chinese */
  culturalNote: text("culturalNote"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type DailyVocabulary = typeof dailyVocabulary.$inferSelect;
export type InsertDailyVocabulary = typeof dailyVocabulary.$inferInsert;

/**
 * Daily content generation job tracking.
 * Records each Heartbeat trigger and its result.
 */
export const dailyContentJobs = mysqlTable("daily_content_jobs", {
  id: int("id").autoincrement().primaryKey(),
  /** Heartbeat task UID from the cron platform */
  scheduleCronTaskUid: varchar("scheduleCronTaskUid", { length: 65 }),
  /** Date this job was for (YYYY-MM-DD) */
  contentDate: varchar("contentDate", { length: 10 }).notNull(),
  /** Job status */
  status: mysqlEnum("status", ["pending", "running", "completed", "failed"]).notNull().default("pending"),
  /** Number of articles generated */
  articlesGenerated: int("articlesGenerated").default(0),
  /** Number of vocabulary items generated */
  vocabularyGenerated: int("vocabularyGenerated").default(0),
  /** Error message if failed */
  errorMessage: text("errorMessage"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  completedAt: timestamp("completedAt"),
});

export type DailyContentJob = typeof dailyContentJobs.$inferSelect;
export type InsertDailyContentJob = typeof dailyContentJobs.$inferInsert;
